config/routes.rb
Rails.application.routes.draw do
  get 'about/payment', to: 'about#payment'
  get 'about', to: 'about#index'
  # devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', sign_up: 'registration' }

  devise_scope :user do
    get 'users/logout' => "devise/sessions#destroy"
  end
  
  post 'cart' => "cart#index"

  get 'seeds', to: 'seeds#index'
  get 'seeds/:id', to: 'seeds#show', as: 'seed', constraints: { id: /\d+/ }
  get 'seeds/:topic', to: 'seeds#topic'
  
  get 'orders/:id', to: 'orders#show', constraints: { id: /\d+/ }
  get 'orders/finished', to: 'orders#finished'
  
  resources :orders

  root to: 'seeds#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :region
  belongs_to :user
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :seed
end

app/models/region.rb
class Region < ApplicationRecord
  has_one :order
end

app/models/seed.rb
class Seed < ApplicationRecord
  mount_uploaders :image, ImageUploader
  serialize :image
  has_many :prices
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  
  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, authentication_keys: [:login]
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end

  def payment
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def authenticate_admin!
    authenticate_user!
    unless current_user.admin?
      flash[:alert] = "Unauthorized Access"
      redirect_to root_path
    end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!

  def index
    @order_input = params[:orders]

    if @order_input.empty?
      flash[:alert] = "Ваша корзина пуста. Добавьте желаемые товары в корзину."
      redirect_to root_path
    else
      @items = JSON.parse(@order_input)
      
      @items.each do |item|
        item["id"] = Seed.find(item["id"])
      end
    end
    @regions = Region.all
    @order = Order.new
    @lastorder = current_user.orders.last
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: :show

  # GET /orders
  # GET /orders.json
  def index
    @orders = current_user.orders.order(id: :desc)
    redirect_to root_path, notice: "У вас не было заказов. Сделайте первый!" if @orders.empty?
    @orders_finished = current_user.orders.where(status: "received")
  end

  def finished
    @orders = current_user.orders.where(status: "received")
    redirect_to root_path, notice: "У вас нет завершенных заказов!" if @orders.empty?
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'order was successfully created.' }
        format.json { render :show, status: :created, location: @order }

        OrderMailer.with(order: @order).new_order_email.deliver_later # sending new-order-email to admin
        OrderMailer.with(order: @order).new_order_to_user_email.deliver_later # sending new-order-email to user
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def correct_user
      @order = current_user.orders.find_by(id: params[:id])
      redirect_to orders_path, notice: "Not authorised to show this order" if @order.nil?
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:full_name, :phone, :status, :region_id, :address, :order, :zip, :user_id)
    end
end

app/controllers/seeds_controller.rb
class SeedsController < ApplicationController

  def index
    @seeds = Seed.order(id: :asc)
  end

  def topic
    if params[:topic] == "conifers"
      @seeds = Seed.order(id: :asc).where(conifers: true)
    elsif params[:topic] == "deciduous"
      @seeds = Seed.order(id: :asc).where(conifers: false)
    else
      return redirect_to root_path, notice: "Неправильная категория!"
    end
    render 'index'
  end

  def show
    @seed = Seed.find(params[:id])
  end

  private

    # Only allow a list of trusted parameters through.
    def seed_params
      params.require(:seed).permit(:title, :latin_title, :description, :usda, :image)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/seeds_helper.rb
module SeedsHelper
end

app/views/about/index.html.erb
<h2 class="my-3">О нас</h2>

app/views/about/payment.html.erb
<p class="h3 my-3">Оплата и доставка</p>
<ul class="list-unstyled">
<li><p class="lead">Мы очень рады что вы решили сделать заказ у нас :) </p></li>
<li><p class="lead">Сделать заказ на нашем сайте очень просто:</p></li>
<ul>
  <li>Добавьте нужные позиции в корзину и оформите заказ</li>
  <li>После оформления заказа, на вашу почту придет письмо с реквизитами для оплаты</li>
  <li>После оплаты мы отправим заказ и пришлем вам номер для отслеживания посылки</li>
</ul>
</ul>
<em>Заказ отправляем Почтой России в течении 1-2 дней после оплаты<br>
Стоимость пересылки зависит от веса, примерно от 200 рублей, прибавляется к сумме заказа</em>

app/views/cart/_form.html.erb
<%= form_with(model: @order) do |form| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(Order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% @order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :order, value: @order_input %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.hidden_field :status, value: "placed" %>

  <div class="form-group">
    <%= form.label "ФИО:" %>
    <%= form.text_field :full_name, class: "form-control", placeholder: "Введите ФИО", value: @lastorder.try(:full_name) %>
  </div>

  <div class="form-group">
    <%= form.label "Телефон:" %>
    <%= form.text_field :phone, class: "form-control", placeholder: "Ваш телефон", value: @lastorder.try(:phone) %>
  </div>

  <div class="form-group">
    <%= form.label "Почтовый индекс:" %>
    <%= form.text_field :zip, class: "form-control", placeholder: "Введите индекс", value: @lastorder.try(:zip) %>
  </div>

  <div class="form-group">
    <label>Регион РФ:</label>
    <select name="order[region_id]" class="custom-select" aria-label="Default select example">
      <option selected value="<%= @lastorder.try(:region).try(:id) %>"><%= @lastorder.try(:region).try(:title) || "Выбирите регион..." %></option>
      <% @regions.each do |region| %>
        <option value="<%= region.id %>"><%= region.title %></option>
      <% end %>
    </select>
  </div>

  <div class="form-group">
    <%= form.label "Адрес:" %>
    <%= form.text_field :address, class: "form-control", placeholder: "Адрес доставки", value: @lastorder.try(:address) %>
  </div>

  <div class="actions">
    <%= form.submit "Разместить заказ", class: "btn btn-primary", onclick: "clear_cart()" %>
    <%= form.submit "Очистить корзину", class: "btn btn-danger my-2", onclick: "return cancel_order()" %>
  </div>
<% end %>

app/views/cart/index.html.erb
<h2 class="my-3">Ваша корзина</h2>
<div>
	<table class="table table-stripped">
		<thead>
			<tr>
				<th class="d-none d-sm-block">#</th>
				<th class="px-0 px-sm-2">Наименование</th>
				<th class="pe-0 pe-sm-2 ps-1 ps-sm-2">Цена</th>
				<th class="px-0 px-sm-2" colspan="3">Количество</th>
				<th class="px-0 px-sm-2" colspan="2">Сумма</th>
			</tr>
		</thead>
		<tbody id="cart" data-url="<%= @items.to_json %>">
		
		<% total_count = 0 %>
		<% total_qty = 0 %>

		<% @items.each_with_index do |item, i| %>
			<tr>
				<td class="d-none d-sm-block"><%= i+1 %></td>
				<td class="px-0 px-sm-2"><%= item["id"].title %></td>
				<td class="pe-0 pe-sm-2 ps-1 ps-sm-2"><%= item["price"] %></td>
				<td class="px-0 px-sm-2 text-right" width="20"><%= link_to(image_tag("/square_remove.png", width: "20", class: "m-0"), "javascript:decrease_count(#{item["id"].id}, #{item["price"]})") %></td>
				<td class="px-0 px-sm-2" width="30">
					<input type="number" min="1" max="99" maxlength="2" onKeyPress="if(this.value.length==2) return false;" 
					onKeyUp="if(this.value>99){this.value = this.value.slice(1, 99);}else if(this.value<1){this.value='1';}" 
					onchange="change_input_count(<%= item['id'].id %>, <%= item['price'].to_i %>, this.value)" style="text-align: center; border: 0; outline: none; width: 40px; padding: 0; margin: 0;" 
					id="count_<%= item["id"].id %>_<%= item["price"] %>" value="<%= item["count"] %>" /></td>
				<td class="px-0 px-sm-2"><%= link_to(image_tag("/square_add.png", width: "20", class: "m-0"), "javascript:increase_count(#{item["id"].id}, #{item["price"]})") %></td>
				<td id="qty_<%= item["id"].id %>_<%= item["price"] %>"><%= item["price"].to_i * item["count"].to_i %></td>
				<td class="px-0 px-sm-2" width="50"><%= link_to(image_tag("/bin.png", width: "20", class: "m-0"), "javascript:delete_item(#{item["id"].id}, #{item["price"]})", onclick: "return confirm('Вы уверены что хотите удалить позицию из корзины?')") %></td>
			</tr>
			<% total_qty += item["price"].to_i * item["count"].to_i %>
			<% total_count += item["count"].to_i %>
		<% end %>
			<tr>
				<td class="d-none d-sm-block"></td>
				<td><strong>Всего</strong></td>
				<td></td>
				<td></td>
				<td class="text-center" id="total_count"><strong><%= total_count %></strong></td>	
				<td></td>
				<td class="px-0 px-sm-2" id="total_qty"><strong><%= total_qty %></strong></td>
			</tr>
		</tbody>
	</table>

	<div class="jumbotron">
		<h4>Заполните форму чтобы сделать заказ</h4><br>

		<%= render partial: "form" %>
		
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Treeseeds</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="/app.js"></script>

    <%# stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# javascript_include_tag 'app', 'data-turbolinks-track': 'reload' %>
    <%# stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <style>
      input::-webkit-outer-spin-button,
      input::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
      }
      input[type="number"] {
        -moz-appearance: textfield;
      }
    </style>

  </head>

  <body class="d-flex flex-column min-vh-100">
    
    <%= render "shared/navbar" %>

    <div class="container">

      <% if notice %>
        <div class="alert alert-success my-3" role="alert">
          <%= notice %>
        </div>
      <% elsif alert %>
        <div class="alert alert-danger my-3" role="alert">
          <%= alert %>
        </div>
      <% end %>


      <%= yield %>

    </div>

    <div class="bg-secondary text-light mt-auto">
      <div class="container pt-5 py-3">
        <p>Все права защищены. Treeseeds.ru 2021</p>
      </div>
    </div>

    <script type="text/javascript">
	
			$(function()
			{
				update_orders_input();
				update_orders_button();
			})

		</script>

  </body>
</html>

app/views/orders/finished.html.erb
<h2 class="my-3">Вашы заказы</h2>


<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="/orders">Активные заказы</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active disabled" href="">Завершенные заказы</a>
  </li>
</ul>
<br>

<% @orders.each do |order| %>
  <% if order.status == "received" %>
    <h4><%= order.full_name %> <%= order.phone %></h4>
    <p><%= order.zip %> <%= order.region.title %> <%= order.address %></p>
    <p>
      <table class="table table-sm">
        <thead>
          <tr>
            <th>Наименование</th>
            <th>Цена</th>
            <th>Количество</th>
            <th>Сумма</th>
          </tr>
        </thead>
        <tbody>
        <% order2 = JSON.parse(order.order) %>

        <% total_count = 0 %>
        <% total_sum = 0 %>

        <% order2.each do |o| %>
      
          <tr>
            <td><%= Seed.find_by(id: o["id"]).title %></td>
            <td><%= o["price"] %></td>
            <td><%= o["count"] %></td>
            <td><%= o["price"] * o["count"] %></td>
          </tr>
          <% total_count += o["count"] %>
          <% total_sum += o["price"] * o["count"] %>
        <% end %>
          <tr>
            <td><strong>Всего </strong></td>
            <td></td>
            <td><strong><%= total_count %></strong></td>
            <td><strong><%= total_sum %></strong></td>
          </tr>
        </tbody>
      </table>
      <% if order.status == "received" %>
        <strong>Статус заказа: </strong>Заказ получен.
      <% end %>
    </p><br>
  <% end %>
<% end %>

app/views/orders/index.html.erb
<h2 class="my-3">Вашы заказы</h2>


<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active disabled" href="#">Активные заказы</a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= "disabled" if @orders_finished.empty? %>" href="/orders/finished">Завершенные заказы</a>
  </li>
</ul>
<br>


<% @orders.each do |order| %>
	<% if order.status != "received" %>
		<div class="border p-3 mb-3">
			<h4><%= order.full_name %> <%= order.phone %></h4>
			<p><%= order.zip %> <%= order.region.title %> <%= order.address %></p>
			<p>
				<table class="table table-sm">
					<thead>
						<tr>
							<th>Наименование</th>
							<th>Цена</th>
							<th>Количество</th>
							<th>Сумма</th>
						</tr>
					</thead>
					<tbody>
					<% order2 = JSON.parse(order.order) %>

					<% total_count = 0 %>
					<% total_sum = 0 %>

					<% order2.each do |o| %>
				
						<tr>
							<td><%= Seed.find_by(id: o["id"]).title %></td>
							<td><%= o["price"] %></td>
							<td><%= o["count"] %></td>
							<td><%= o["price"] * o["count"] %></td>
						</tr>
						<% total_count += o["count"] %>
						<% total_sum += o["price"] * o["count"] %>
					<% end %>
						<tr>
							<td><strong>Всего </strong></td>
							<td></td>
							<td><strong><%= total_count %></strong></td>
							<td><strong><%= total_sum %></strong></td>
						</tr>
					</tbody>
				</table>
				<% if order.status == "placed" %>
					<strong>Статус заказа: </strong>Заказ размещен.
				<% elsif order.status == "paid" %>
					<strong>Статус заказа: </strong>Заказ оплачен. Ожидает отправки.
				<% elsif order.status == "sent" %>
					<strong>Статус заказа: </strong>Заказ отправлен.
				<% end %>
			</p>
		</div>
	<% end %>
<% end %>

app/views/orders/show.html.erb
<h2 class="my-3">Ваш заказ</h2>

<div class="border p-3 mb-3">
	<h4><%= @order.full_name %> <%= @order.phone %></h4>
	<p>Адрес: <%= @order.zip %> <%= @order.region.title %> <%= @order.address %></p>

	<table class="table table-sm">
		<thead>
			<tr>
				<th>Наименование</th>
				<th>Цена</th>
				<th>Количество</th>
				<th>Сумма</th>
			</tr>
		</thead>
		<tbody>
		<% order2 = JSON.parse(@order.order) %>

		<% total_count = 0 %>
		<% total_sum = 0 %>

		<% order2.each do |o| %>
	
			<tr>
				<td><%= Seed.find_by(id: o["id"]).title %></td>
				<td><%= o["price"] %></td>
				<td><%= o["count"] %></td>
				<td><%= o["price"] * o["count"] %></td>
			</tr>
			<% total_count += o["count"] %>
			<% total_sum += o["price"] * o["count"] %>
		<% end %>
			<tr>
				<td><strong>Всего </strong></td>
				<td></td>
				<td><strong><%= total_count %></strong></td>
				<td><strong><%= total_sum %></strong></td>
			</tr>
		</tbody>
	</table>
</div>

app/views/seeds/_form.html.erb
<%= form_with(model: seed) do |form| %>
  <% if seed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seed.errors.count, "error") %> prohibited this seed from being saved:</h2>

      <ul>
        <% seed.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :latin_title %>
    <%= form.text_field :latin_title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 10, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :usda %>
    <%= form.text_field :usda, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seeds/edit.html.erb
<h1 class="my-3">Editing Seed</h1>

<%= render 'form', seed: @seed %>

<%= link_to 'Show', @seed %> |
<%= link_to 'Back', seeds_path %>

app/views/seeds/index.html.erb
<p class="h3 my-3">Семена деревьев</p>
<div class="row justify-content-center justify-content-sm-start">

  <% @seeds.each do |seed| %>
    <% if seed.image? %>
      <div class="col col-11 col-sm-4 col-md-3 col-lg-2 p-0 m-0">
        <div class="p-0 m-1">
          <%= link_to(image_tag(seed.image.first.thumb400.url, alt: seed.title, class: "img-thumbnail w-100"), seed) %>
          <div class="mx-1">
            <p class="text-left m-0" style="font-family: 'Roboto', sans-serif; max-width: 200px;"><%= seed.title %></p>
            <% seed.prices.each do |price| %>
              <% if seed.availability == true %>
                <button class="btn btn-success btn-sm" onClick="add_to_cart(<%= seed.id %>, <%= price.price %>)">В корзину</button>
                <br>
                <%= price.amount %>
                <%= price.unit %>
                <%= price.price %> р. <br>
              <% else %>
                <button class="btn btn-secondary btn-sm" disabled>Нет в наличии</button>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

</div>
<br>

app/views/seeds/new.html.erb
<h1 class="my-3">New Seed</h1>

<%= render 'form', seed: @seed %>

<%= link_to 'Back', seeds_path %>

app/views/seeds/show.html.erb
<p class="h2 my-3" style="font-family: 'Roboto', sans-serif;">
  <%= @seed.title %> (<%= @seed.latin_title %>)
</p>

<div class="row">
  <div class="col-md-5 my-3">
    <p><%= image_tag(@seed.image.first.thumb.url, alt: @seed.title, class: "img-fluid", id: "img") %></p>
    <%  if @seed.image.length > 1 %>
      <% @seed.image.each_with_index do |image, i| %>
        <%= image_tag(image.thumb100.url, class: "img-fluid p-1", onclick: "javascript:change_img('#{image.thumb.url}');") %>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-7 my-3">
    <p>
      <strong>Зона морозостойкости USDA:</strong>
      <%= @seed.usda %>
    </p>
    <p>
    <% @seed.prices.each do |price| %>
      <% if @seed.availability == true %>
        <button class="btn btn-success btn-sm m-1" onClick="add_to_cart(<%= @seed.id %>, <%= price.price %>)">В корзину</button>
        <%= price.amount %>
        <%= price.unit %>
        <%= price.price %> р. <br>
      <% else %>
        <button class="btn btn-secondary btn-sm m-1" disabled>Нет в наличии</button>
      <% end %>
    <% end %>
    
    </p>
    <p>
      <strong>Описание:</strong> 
      <%= simple_format(@seed.description) %>
    </p>
  </div>
</div>



<%# link_to 'Edit', edit_seed_path(@seed) %>
<%# link_to 'Back', seeds_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light sticky-top border-bottom" style="background-color: #f3f3f3;">
  <div class="container-fluid pr-0">
    <a class="navbar-brand" href="/">Treeseeds</a>
    <button class="navbar-toggler mx-1 ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Все семена', '/seeds', class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Хвойные', '/seeds/conifers', class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Лиственные', '/seeds/deciduous', class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%# link_to 'О нас', '/about', class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Оплата и доставка', '/about/payment', class: "nav-link" %>
        </li>
        <%# <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li> %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <%= link_to 'Admin Panel',  admin_root_path, class: "nav-link" if current_user.admin? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.username %></a>
            
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to 'Мои заказы', orders_path, class:"dropdown-item" if current_user.orders.any? %>
              <%= link_to 'Изменить профиль', edit_user_registration_path, class:"dropdown-item" %>
              <%= link_to 'Выйти', destroy_user_session_path, method: :delete, class:"dropdown-item" %>
            </div>
          </li>

        <% else %>
            <%= link_to 'Войти', new_user_session_path, class:"nav-link" %>
            <%= link_to 'Регистрация', new_user_registration_path, class:"nav-link" %>
        <% end %>

        
      </ul>
    </div>
    <%= form_with url: "/cart", method: :post do |form| %>
      <%= form.hidden_field "orders", id: "orders_input" %>
      <%= form.submit "Корзина", id: "orders_button", class: "btn btn-danger" %>

      <%# image_submit_tag("/shopping-cart.png", width: "40", class: "p-1 mb-0 mt-1", id: "orders_button") %>
    <% end %>
  </div>
</nav>